services:
  - type: web
    name: pontes-de-papel
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false

