services:
  - type: web
    name: website-pontes-de-papel
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false

